=== paulapelegriela/DAM_portafolio/DAM1/Lenguaje de marcas/XML/problema_2.dtd
<!ELEMENT agenda (contacto+)>

<!ELEMENT contacto (nombre, telefono, email?, etiquetas)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT etiquetas (etiqueta+)>

<!ELEMENT etiqueta (#PCDATA)>

=== paulapelegriela/DAM_portafolio/DAM1/Lenguaje de marcas/XML/problema_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "problema_2.dtd">

<agenda>

    <contacto>
        <nombre>Júlia Fortuny</nombre>
        <telefono>612345678</telefono>
        <email>juliaa123@email.com</email>

        <etiquetas>
            <etiqueta>amiga</etiqueta>
        </etiquetas>
    </contacto>

    <contacto>
        <nombre>Brandon Vega</nombre>
        <telefono>698745321</telefono>

        <etiquetas>
            <etiqueta>amigo</etiqueta>
            <etiqueta>pareja</etiqueta>
        </etiquetas>
    </contacto>

    <contacto>
        <nombre>Angela Sánchez</nombre>
        <telefono>654987321</telefono>
        <email>angela.sanchez@email.com</email>

        <etiquetas>
            <etiqueta>amiga</etiqueta>
            <etiqueta>familia</etiqueta>
        </etiquetas>
    </contacto>

</agenda>
